module EverywhereDense (original_a, geometry_a) where

original_a :: Char -> [ String ]
original_a 'a' = [ "a", "an", "anyone", "anvil", "acronym", "ask", "arcane" ]
original_a 'b' = [ "by", "beg", "black", "but", "burden", "be", "bunyip" ]
original_a 'c' = [ "could", "cyan", "cloud", "can't", "canyon", "cold" ]
original_a 'd' = [ "don't", "do", "dig", "death", "did", "dense", "down" ]
original_a 'e' = [ "everywhere", "even", "extreme", "either", "egg" ]
original_a 'f' = [ "from", "for", "feather", "freezing", "felt" ]
original_a 'g' = [ "go",  "good", "green", "grass", "get", "golden", "god" ]
original_a 'h' = [ "have",  "heart", "help", "happy", "hard", "hey", "hot", "he", "his", "her" ]
original_a 'i' = [ "I", "it", "is", "isn't",  "iron", "incomplete", "into", "intimate", "I'll", "in" ]
original_a 'j' = [ "join", "joy",  "journey", "jail", "jump", "jazz" ]
original_a 'k' = [ "knit", "keepsake",  "know", "knife", "kept" ]
original_a 'l' = [ "let",  "length", "love", "learn", "lead", "lay" ]
original_a 'm' = [ "my", "me",  "marry", "mauve", "more", "melt", "maybe", "man"  ]
original_a 'n' = [ "no", "not",  "next", "need", "naked", "network" ]
original_a 'o' = [ "oh",   "ordinary", "other", "on", "out", "of", "off"  ]
original_a 'p' = [ "pink",  "pass", "put", "package", "purpose", "paid" ]
original_a 'q' = [ "quiet", "queen", "queue", "quiz", "quite", "quake", "quaint" ]
original_a 'r' = [  "random", "red", "related", "rode", "rot", "round"  ]
original_a 's' = [  "she", "sex", "sure", "sent", "sudden", "silver", "sigh", "sort"  ]
original_a 't' = [  "to", "the", "tale", "tall", "take", "toward", "tongue"  ]
original_a 'u' = [  "under", "up", "until", "upset", "unless"  ]
original_a 'v' = [ "version", "vow", "view", "vision", "vary", "verb" ]
original_a 'w' = [ "woman", "wild", "when", "were", "wizard", "we", "won't"  ]
original_a 'x' = [  "x-ray", "X-Men", "x-rated", "XXXX", "xenon"  ]
original_a 'y' = [ "yes", "yesterday", "year", "yet", "your", "you", "yearn" ]
original_a 'z' = [ "zither", "zebra", "zoo", "zip", "zoom" ]
original_a _   = []


geometry_a :: Char -> [ String ]
geometry_a 'a' = [ "a", "adjacent", "anyone", "angle", "acronym", "affine", "asymptote", "angel", "azimuth", "aliquot" ]
geometry_a 'b' = [ "by", "be", "between", "but", "both", "box", "backward", "blend" ]
geometry_a 'c' = [ "could", "cloud", "Cantor", "can", "colloid", "corner", "catch", "come", "continuum" ]
geometry_a 'd' = [ "don't", "do", "did", "dense", "dust", "down", "dead", "dry", "discrete"  ]
geometry_a 'e' = [ "everywhere", "even", "expand", "either", "exponent", "emergent", "else", "edge"  ]
geometry_a 'f' = [ "from", "for", "fill", "find", "free", "feel", "few", "fewer" ]
geometry_a 'g' = [ "go", "God", "get", "geometry", "glory", "growth", "gone", "gain" ]
geometry_a 'h' = [ "have",  "heart", "he", "his", "her", "hold", "Hell", "Heaven", "how"  ]
geometry_a 'i' = [ "I", "it", "is", "isn't",  "in", "incomplete", "into", "item", "infinite"  ]
geometry_a 'j' = [ "join", "journey", "joy", "jump", "jet", "jaunt" ]
geometry_a 'k' = [ "knit",  "know", "knife", "kept", "keep", "knight", "kill", "king" ]
geometry_a 'l' = [ "let", "line", "length", "love", "learn", "lead", "lie", "low", "left", "labyrinth" ]
geometry_a 'm' = [ "my", "me", "more", "mass", "maybe", "man", "major", "minor", "matrix", "maze"  ]
geometry_a 'n' = [ "no", "not", "next", "need", "network", "never", "none", "new", "node", "near" ]
geometry_a 'o' = [ "onward", "oh", "ordinal", "other", "on", "out", "of", "off", "one" ]
geometry_a 'p' = [ "pass", "put", "package", "purpose", "point", "path", "plane", "part" ]
geometry_a 'q' = [ "quiet", "queen", "queue", "quiz", "quite" ]
geometry_a 'r' = [  "recursive", "random", "related", "round", "rear", "rotate", "run", "right"  ]
geometry_a 's' = [  "she", "sure","sequence", "swap", "send", "seek", "sort", "split", "size", "sine"  ]
geometry_a 't' = [  "topos", "to", "the", "tale", "take", "top", "tangent", "tensor", "tranquil", "terminus", "term", "toward"  ]
geometry_a 'u' = [  "under", "unquiet", "up", "until", "unless", "unlike", "ultra", "unknown", "usual" ]
geometry_a 'v' = [  "volume", "vertex", "void", "version", "violent", "variable", "vision", "very", "view" ]
geometry_a 'w' = [ "woman", "when", "were", "where", "wizard", "we", "won't", "watch"  ]
geometry_a 'x' = [  "x-ray", "x-rated", "xenon", "xerox"   ]
geometry_a 'y' = [ "yes", "year", "yet", "your", "you", "you're" ]
geometry_a 'z' = [  "zone", "zero", "zip", "zoom" ]
geometry_a _   = []
